// <auto-generated />
using System;
using CMCDemo.Persistence.Common;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CMCDemo.Persistence.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    partial class RepositoryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CMCDemo.Domain.Entities.Community_Medical_Centers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MedicalCenterAddressId")
                        .HasColumnType("int");

                    b.Property<string>("MedicalCenterManager")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MedicalCenterName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.HasKey("Id");

                    b.HasIndex("MedicalCenterAddressId");

                    b.ToTable("Community_Medical_Centers", (string)null);
                });

            modelBuilder.Entity("CMCDemo.Domain.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Community_Medical_CentersId")
                        .HasColumnType("int");

                    b.Property<string>("DepartmentChief")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Community_Medical_CentersId");

                    b.ToTable("Departments", (string)null);
                });

            modelBuilder.Entity("CMCDemo.Domain.Entities.MedicalCenterAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BuildingNumber")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Landmark")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Locality")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("PostCode")
                        .HasColumnType("int");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("StreetName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("MedicalCenterAddress", (string)null);
                });

            modelBuilder.Entity("CMCDemo.Domain.Entities.ProfessionalStaff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Community_Medical_CentersId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateBirthed")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateJoinedCenter")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateLeftCenter")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StaffAddressId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Community_Medical_CentersId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("StaffAddressId");

                    b.ToTable("ProfessionalStaffs", (string)null);
                });

            modelBuilder.Entity("CMCDemo.Domain.Entities.Ref_Disciplines", b =>
                {
                    b.Property<int>("Ref_DisciplinesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Ref_DisciplinesId"));

                    b.Property<DateTime?>("DateObtained")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("DisciplinesDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisciplinesName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProfessionalStaffId")
                        .HasColumnType("int");

                    b.HasKey("Ref_DisciplinesId");

                    b.HasIndex("ProfessionalStaffId");

                    b.ToTable("Ref_Disciplines", (string)null);
                });

            modelBuilder.Entity("CMCDemo.Domain.Entities.StaffAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BuildingNumber")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Landmark")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Locality")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("PostCode")
                        .HasColumnType("int");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("StreetName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("StaffAddresses", (string)null);
                });

            modelBuilder.Entity("CMCDemo.Domain.Entities.Community_Medical_Centers", b =>
                {
                    b.HasOne("CMCDemo.Domain.Entities.MedicalCenterAddress", "MedicalCenterAddress")
                        .WithMany("MedicalCenters")
                        .HasForeignKey("MedicalCenterAddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MedicalCenterAddress");
                });

            modelBuilder.Entity("CMCDemo.Domain.Entities.Department", b =>
                {
                    b.HasOne("CMCDemo.Domain.Entities.Community_Medical_Centers", "Community_Medical_Centers")
                        .WithMany("Departments")
                        .HasForeignKey("Community_Medical_CentersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Community_Medical_Centers");
                });

            modelBuilder.Entity("CMCDemo.Domain.Entities.ProfessionalStaff", b =>
                {
                    b.HasOne("CMCDemo.Domain.Entities.Community_Medical_Centers", "Community_Medical_Centers")
                        .WithMany("Staffs")
                        .HasForeignKey("Community_Medical_CentersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CMCDemo.Domain.Entities.Department", "Department")
                        .WithMany("ProfessionalStaff")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CMCDemo.Domain.Entities.StaffAddress", "StaffAddress")
                        .WithMany("ProfessionalStaff")
                        .HasForeignKey("StaffAddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Community_Medical_Centers");

                    b.Navigation("Department");

                    b.Navigation("StaffAddress");
                });

            modelBuilder.Entity("CMCDemo.Domain.Entities.Ref_Disciplines", b =>
                {
                    b.HasOne("CMCDemo.Domain.Entities.ProfessionalStaff", "ProfessionalStaff")
                        .WithMany("Ref_Disciplines")
                        .HasForeignKey("ProfessionalStaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProfessionalStaff");
                });

            modelBuilder.Entity("CMCDemo.Domain.Entities.Community_Medical_Centers", b =>
                {
                    b.Navigation("Departments");

                    b.Navigation("Staffs");
                });

            modelBuilder.Entity("CMCDemo.Domain.Entities.Department", b =>
                {
                    b.Navigation("ProfessionalStaff");
                });

            modelBuilder.Entity("CMCDemo.Domain.Entities.MedicalCenterAddress", b =>
                {
                    b.Navigation("MedicalCenters");
                });

            modelBuilder.Entity("CMCDemo.Domain.Entities.ProfessionalStaff", b =>
                {
                    b.Navigation("Ref_Disciplines");
                });

            modelBuilder.Entity("CMCDemo.Domain.Entities.StaffAddress", b =>
                {
                    b.Navigation("ProfessionalStaff");
                });
#pragma warning restore 612, 618
        }
    }
}
